### ISSUE TITLE
Any docker image available?

### ISSUE THREAD

**Issue by C-Fu** [arevindh/pihole-speedtest#97]
Please consider, thanks!

**Comment by corasaniti** [comment]
@C-Fu You can perform the installation steps within the official Docker image. 
And if you wish to commit your changes so that you have your Docker image modified.

**Comment by corasaniti** [comment]
however I have many problems applying the installation in docker. 
So I abandoned the mod. 
I am very sorry because it is very beautiful
A docker image would therefore be welcome. please build docker image :-) 
Thanks

**Comment by arevindh** [comment]
> however I have many problems applying the installation in docker. So I abandoned the mod. I am very sorry because it is very beautiful A docker image would therefore be welcome. please build docker image :-) Thanks

@corasaniti It is getting updated every release.

**Comment by arevindh** [comment]
@C-Fu I'm currently working on docker images. Might take a week .

**Comment by arevindh** [comment]
Try this 

```
version: "3"

# More info at https://github.com/arevindh/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: arevindh/pihole:v5.9
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/arevindh/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ```
